# Generated by Django 2.2.19 on 2021-03-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20210123_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('elecciones', 'Elecciones'), ('referendum', 'Referendum')], default='election', max_length=250),
        ),
    ]
